### ISSUE TITLE
Support for Scrypt mining chips. (BM1489)

### ISSUE THREAD

**Issue by IdotMaster1** [skot/bitaxe#24]
Will bitaxe ever support scrypt chips like the BM1489? I would really like to see a scrypt version of this!\]

**Comment by skot** [comment]
I don't really know anything about the BM1489 or scrypt, so prolly not anytime soon. Unless you want to fork it and give it a shot!

**Comment by ffrediani** [comment]
@skot what would take to understand the BM1489 ASIC and make a scrypt version of Bitaxe ? Given the ASIC looks like the BM1366 physically, do you think it would have a too much different pin configuration ?

Other than that would also require any significant changes on the ESP32 code ?

Since BM1366 is an undocumented ASIC what would take to get the necessary information from it as it was for BM1366 ?
