### ISSUE TITLE
Barrel to wire screw terminal adapter is no good for powering the bitaxe

### ISSUE THREAD

**Issue by skot** [skot/bitaxe#46]
Some power supplies come with these 2.5mm barrel to wire screw terminal adapters:
<img width="236" alt="image" src="https://github.com/skot/bitaxe/assets/140785/e216024e-3474-4c13-a2f4-781b84b40d2d">

Unfortunately they are too high resistance for use in powering the bitaxe. They will drop the input voltage too much and/or get super hot. It's best to wire it directly.

**Comment by BastelPichi** [comment]
USB c requires extra Chip to get proper Power. Also, at 5v, USB c can "only" handle 5a (Most chargers dont do). USB c Gear is quite expensive currently so I wouldnt so that.

Im actually quite Happy with spade connectors, as you can and should Just get an proper Power supply already.

Abstract Idea: use ATX Power supply connectors...

**Comment by DocBrown101** [comment]
The only alternative I can see here is an XT30 or XT60 connection.
