### ISSUE TITLE
ASIC chip temp not working

### ISSUE THREAD

**Issue by skot** [skot/bitaxe#59]
The pins I thought were the on-die chip temp sensor don't seem to be working. the EMC2101 will read 127ºC, the max temp all the time.

It's probably best to DNP resistors R7 and R8 to disconnect the EMC2101 from the BM1366 for now. (it will read 0ºC after that)

<img width="807" alt="image" src="https://github.com/skot/bitaxe/assets/140785/2b5ef758-26ed-4b16-8a51-8c6c2d0a0f97">

**Comment by SatoshyBoy** [comment]
Hi Skot.

My sensor is reading the temperature. I added a pretty good thermal pad on the chip and finally got a temperature below the maximum. It is reading temperature around 63C.

Another detail that I noticed. After adding the thermal pad, the current decreases by 1A for the same hash/rate. I didn't expect that.

**Comment by skot** [comment]
> My EMC2101 is reading the temperature. 

Is this on the bitaxeUltra with the BM1366?

**Comment by SatoshyBoy** [comment]
Sorry, It is the BM1397. I didn't notice that this topic is for the ULTRA. But BM1397 also has an issue with the temperature. I was reading 127 every time.  

But there is something weird with BM1397, too. I can change the measured temperature by only changing the Vin. Usually, the bitaxe uses 5V, but if you try other voltage inputs, it has an effect on the temperature. It doesn't make sense because the VDD is always the same 1.4v, and power consumption (P=Vin*I) is constant.
 
Moreover, the output has a square form, which also doesn't make sense. (Yellow: temp_P. Purple: temp_N. White: temp_P - temp_N)
![SDS00001](https://github.com/skot/bitaxe/assets/132848052/e5e3005b-fa24-4952-aefc-b1b95ac01e71)

**Comment by skot** [comment]
When you get that square wave on the ASIC die temp pins, is it also connected to the EMC2101?

Those die temp pins are connected to a diode (or transistor) on the die. To measure the temperature you put two different currents through it and the difference in forward voltage is proportional to the temperature. That would be one explanation for the square wave.

It also seems like you have a soldering problem and/or the ASIC is damaged. I have been able to read the chip temp just fine on several BM1397.

**Comment by SatoshyBoy** [comment]
The EMC2101 is connected. I didn't know it has an active connection for parasitic resistance in series.

**Comment by skot** [comment]
Confirmed the BM1366 does not have internal temp diode pins :(
